%% @dictionary main { email: "^[a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", url: "^https?://[^\s]+$" }
erDiagram
    BaseEntity { 
        ISODate createdAt %% @validate { required: true, autoGenerate: true } @ui {readOnly: true}
        ISODate updatedAt %% @validate { required: true, autoUpdate: true } @ui {readOnly: true}

        %% @abstract
    }


    Account {
        ISODate expiredAt %% @validate { required: false }
    
        %% @ui { title: "Accounts", buttonLabel: "Manage Accounts" }
    	%% @include BaseEntity
        %% @ui updatedAt { displayPages: "details", displayAfterField: 'createdAt' } 
    }


    User {
        String username          %% @validate { required: true, min_length: 3, max_length: 50 }, @unique
        String email             %% @validate { required: true, min_length: 8, max_length: 50, pattern: { regex: "dictionary=main.email", message: "Bad email address format" } }, @unique
        String password          %% @validate { required: true, min_length: 8 } @ui { displayPages: "details", display: "secret" }
        String firstName         %% @validate { required: true, min_length: 3, max_length: 100 }, @ui { displayName: "First Name" }
        String lastName          %% @validate { required: true, min_length: 3, max_length: 100 }, @ui { displayName: "Last Name" }
        String gender            %% @validate { required: false, enum: { values: ["male", "female", "other"], message: "must be male or female" } }
        ISODate dob              %% @validate { required: false }
        Boolean isAccountOwner   %% @validate { required: true }, @ui { displayName: "Owner"}
    
        %% @ui { title: "Users", buttonLabel: "Manage Users", description: "Manage User Profile" }
    	%% @service auth.cookies.redis 
    	%% @include BaseEntity  
        %% @ui createdAt { displayPages: "summary" } 
        %% @operations ["read", "create", "update"]
    }


    Profile {
        String name          %% @validate { required: true, max_length: 100 }
        JSON preferences     %% @validate { required: false } @ui { displayPages: "details"}
        Integer radiusMiles  %% @validate { required: false, ge: 0 }
    
        %% @ui { title: "Profile", buttonLabel: "Manage User Profiles", description: "Manage User Preferences" }
    	%% @include BaseEntity
    	%% @unique name + userId
    }


    TagAffinity {
        String tag            %% @validate { required: true, max_length: 50 }
        Integer affinity      %% @validate { required: true, ge: -100, le: 100 }
    
        %% @ui { title: "Tag Affinity", buttonLabel: "Manage Event Affinity" }
    	%% @include BaseEntity
    	%% @unique profileId + tag
    }


    Event {
        String url                         %% @validate { required: true, pattern: { regex: "dictionary=main.url", message: "Bad URL format" } }
        String title                       %% @validate { required: true, max_length: 200 }
        ISODate dateTime                   %% @validate { required: true }
        String location                    %% @validate { required: false, max_length: 200 }
        Number cost                        %% @validate { required: false, ge: 0 } @ui { displayPages: "details"}
        Integer numOfExpectedAttendees     %% @validate { required: false, ge: 0 } @ui { displayPages: "details"}
        String recurrence                  %% @validate { required: false, enum: { values: ["daily", "weekly", "monthly", "yearly"] } } @ui { displayPages: "details"}
        Array[String] tags                 %% @validate { required: false } @ui { displayPages: "details"}
    
        %% @ui { title: "Events", buttonLabel: "Manage Events" }
    	%% @include BaseEntity
    }


    UserEvent {
        Boolean attended     %% @validate { required: false }
        Integer rating       %% @validate { required: false, ge: 1, le: 5 }
        String note          %% @validate { required: false, max_length: 500 } @ui { displayPages: "details"}
    
        %% @ui { title: "User Events", buttonLabel: "Manage Event Attendance" }
    	%% @include BaseEntity
    }


    Url {
        String url       %% @validate { required: true, pattern: { regex: "main.url", message: "Bad URL format" } }
        JSON params      %% @validate { required: false }
    
        %% @ui { title: "Url", buttonLabel: "Manage Urls", description: "Manage Event Urls" }
    	%% @include BaseEntity
    }

    Crawl {
        ISODate lastParsedDate             %% @validate { required: false }
        JSON parseStatus                   %% @validate { required: false }
        Array[String] errorsEncountered    %% @validate { required: false }
    
        %% @ui { title: "Crawls", buttonLabel: "Manage Crawls", description: "Manage Crawls of Event sites" }
    	%% @include BaseEntity
        %% @operations [ "read", "delete" ]
    }


    Account ||--o{ User: ""
    User ||--o{ Profile: ""
    Profile ||--o{ TagAffinity: ""
    User ||--o{ UserEvent: ""
    Event ||--o{ UserEvent: ""
    Url ||--o{ Crawl: ""


