_relationships:
- source: Account
  target: User
- source: User
  target: Profile
- source: Profile
  target: TagAffinity
- source: User
  target: UserEvent
- source: Event
  target: UserEvent
- source: Url
  target: Crawl
_dictionaries:
  pattern:
    email: ^[a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,}$
    url: ^https?://[^s]+$
_services:
- auth.cookies.redis
_inherited_entities:
- BaseEntity
_entities:
  BaseEntity:
    fields:
      createdAt:
        type: ISODate
        required: true
        autoGenerate: true
      updatedAt:
        type: ISODate
        required: true
        autoUpdate: true
    relationships: []
  Account:
    fields:
      expiredAt:
        type: ISODate
        required: false
    relationships:
    - User
    inherits:
    - BaseEntity
  User:
    fields:
      username:
        type: String
        ui_metadata:
          displayName: whos your daddy?
        required: true
        minLength: 3
        maxLength: 50
      email:
        type: String
        required: true
        minLength: 8
        maxLength: 50
        pattern: dictionary=pattern.email
        pattern.message: Bad email address format
      password:
        type: String
        required: true
        minLength: 8
      firstName:
        type: String
        required: true
        minLength: 3
        maxLength: 100
      lastName:
        type: String
        required: true
        minLength: 3
        maxLength: 100
      gender:
        type: String
        required: false
        enum:
        - male
        - female
        - other
        enum.message: must be male or female
      isAccountOwner:
        type: Boolean
        required: true
    relationships:
    - Profile
    - UserEvent
    unique:
    - - username
    - - email
    inherits:
    - BaseEntity
    services:
    - auth.cookies.redis
  Profile:
    fields:
      name:
        type: String
        required: true
        maxLength: 100
      preferences:
        type: JSON
        required: false
      radiusMiles:
        type: Integer
        required: false
        min: 0
    relationships:
    - TagAffinity
    inherits:
    - BaseEntity
    unique:
    - - name
      - userId
  TagAffinity:
    fields:
      tag:
        type: String
        required: true
        maxLength: 50
      affinity:
        type: Integer
        required: true
        min: -100
        max: 100
    relationships: []
    inherits:
    - BaseEntity
    unique:
    - - profileId
      - tag
  Event:
    fields:
      url:
        type: String
        required: true
        pattern: dictionary=pattern.url
        pattern.message: Bad URL format
      title:
        type: String
        required: true
        maxLength: 200
      dateTime:
        type: ISODate
        required: true
      location:
        type: String
        required: false
        maxLength: 200
      cost:
        type: Number
        required: false
        min: 0
      numOfExpectedAttendees:
        type: Integer
        required: false
        min: 0
      recurrence:
        type: String
        required: false
        enum:
        - daily
        - weekly
        - monthly
        - yearly
      tags:
        type: Array[String]
        required: false
    relationships:
    - UserEvent
    inherits:
    - BaseEntity
  UserEvent:
    fields:
      attended:
        type: Boolean
        required: false
      rating:
        type: Integer
        required: false
        min: 1
        max: 5
      note:
        type: String
        required: false
        maxLength: 500
    relationships: []
    inherits:
    - BaseEntity
  Url:
    fields:
      url:
        type: String
        required: true
        pattern: dictionary=pattern.url
        pattern.message: Bad URL format
      params:
        type: JSON
        required: false
    relationships:
    - Crawl
    inherits:
    - BaseEntity
  Crawl:
    fields:
      lastParsedDate:
        type: ISODate
        required: false
      parseStatus:
        type: JSON
        required: false
      errorsEncountered:
        type: Array[String]
        required: false
    relationships: []
    inherits:
    - BaseEntity
