_relationships:
- source: Account
  target: User
- source: User
  target: Profile
- source: Profile
  target: TagAffinity
- source: User
  target: UserEvent
- source: Event
  target: UserEvent
- source: Url
  target: Crawl
BaseEntity:
  fields:
    _id:
      type: ObjectId
      required: true
      autoGenerate: true
    createdAt:
      type: ISODate
      required: true
      autoGenerate: true
    updatedAt:
      type: ISODate
      required: true
      autoUpdate: true
  relations: []
Account:
  fields:
    expiredAt:
      type: ISODate
      required: false
  inherits:
  - BaseEntity
  relations:
  - User
User:
  fields:
    accountId:
      type: ObjectId
      required: true
    username:
      type: String
      required: true
      minLength: 3
      maxLength: 50
    email:
      type: String
      required: true
      minLength: 8
      maxLength: 50
      pattern: ^[a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
    password:
      type: String
      required: true
      minLength: 8
    firstName:
      type: String
      required: true
      maxLength: 100
    lastName:
      type: String
      required: true
      maxLength: 100
    gender:
      type: String
      required: false
      enum:
      - male
      - female
      - other
    isAccountOwner:
      type: Boolean
      required: true
  inherits:
  - BaseEntity
  relations:
  - Profile
  - UserEvent
Profile:
  fields:
    userId:
      type: ObjectId
    name:
      type: String
    preferences:
      type: JSON
    radiusMiles:
      type: Integer
  relations:
  - TagAffinity
TagAffinity:
  fields:
    profileId:
      type: ObjectId
    tag:
      type: String
    affinity:
      type: Integer
  relations: []
Event:
  fields:
    url:
      type: String
    title:
      type: String
    dateTime:
      type: ISODate
    location:
      type: String
    cost:
      type: Number
    numOfExpectedAttendees:
      type: Integer
    recurrence:
      type: String
  relations:
  - UserEvent
UserEvent:
  fields:
    userId:
      type: ObjectId
    eventId:
      type: ObjectId
    attended:
      type: Boolean
    rating:
      type: Integer
    note:
      type: String
  relations: []
Url:
  fields:
    url:
      type: String
    params:
      type: JSON
  relations:
  - Crawl
Crawl:
  fields:
    urlId:
      type: ObjectId
    lastParsedDate:
      type: ISODate
    parseStatus:
      type: JSON
  relations: []
