_relationships:
- source: Account
  target: User
- source: User
  target: Profile
- source: Profile
  target: TagAffinity
- source: User
  target: UserEvent
- source: Event
  target: UserEvent
- source: Url
  target: Crawl
_dictionaries:
  main:
    email: ^[a-zA-Z0-9](.?[a-zA-Z0-9_+%-])*@[a-zA-Z0-9-]+(.[a-zA-Z0-9-]+)*.[a-zA-Z]{2,}$
    url: ^https?://[^s]+$
_services:
- auth.cookies.redis
_included_entities: []
_entities:
  BaseEntity:
    fields:
      createdAt:
        type: Date
        autoGenerate: true
        ui:
          readOnly: true
      updatedAt:
        type: Datetime
        autoUpdate: true
        ui:
          readOnly: true
          clientEdit: true
    relationships: []
    abstract: true
  Account:
    fields:
      expiredAt:
        type: Date
        required: false
      createdAt:
        type: Date
        autoGenerate: true
        ui:
          readOnly: true
          displayAfterField: '-1'
      updatedAt:
        type: Datetime
        autoUpdate: true
        ui:
          readOnly: true
          clientEdit: true
          displayAfterField: createdAt
          displayPages: details
    relationships:
    - User
    ui:
      title: Accounts
      buttonLabel: Manage Accounts
    unique: []
    service: []
  User:
    fields:
      username:
        type: String
        required: true
        min_length: 3
        max_length: 50
      email:
        type: String
        required: true
        min_length: 8
        max_length: 50
        pattern:
          regex: dictionary=main.email
          message: Bad email address format
      password:
        type: String
        required: true
        min_length: 8
        ui:
          displayPages: details
          display: secret
      firstName:
        type: String
        required: true
        min_length: 3
        max_length: 100
        ui:
          displayName: First Name
      lastName:
        type: String
        required: true
        min_length: 3
        max_length: 100
        ui:
          displayName: Last Name
      gender:
        type: String
        required: false
        enum:
          values:
          - male
          - female
          - other
          message: must be male or female
      dob:
        type: Date
        required: false
      isAccountOwner:
        type: Boolean
        required: true
        ui:
          displayName: Owner
      netWorth:
        type: Currency
        ge: 0
        le: 10000000
      accountId:
        type: ObjectId
        ui:
          displayName: Account
          show:
            endpoint: account
            displayInfo:
            - displayPages: summary
              fields:
              - createdAt
            - displayPages: edit|create
              fields:
              - createdAt
              - expiredAt
        required: true
      createdAt:
        type: Date
        autoGenerate: true
        ui:
          readOnly: true
          displayAfterField: '-1'
          displayPages: summary
      updatedAt:
        type: Datetime
        autoUpdate: true
        ui:
          readOnly: true
          clientEdit: true
          displayAfterField: '-1'
    relationships:
    - Profile
    - UserEvent
    unique:
    - - username
    - - email
    ui:
      title: Users
      buttonLabel: Manage Users
      description: Manage User Profile
    service:
    - auth.cookies.redis
    operations: rcu
  Profile:
    fields:
      name:
        type: String
        required: true
        max_length: 100
      preferences:
        type: String
        required: false
        ui:
          displayPages: details
      radiusMiles:
        type: Integer
        required: false
        ge: 0
      userId:
        type: ObjectId
        ui:
          show:
            displayInfo:
            - displayPages: summary
              fields:
              - email
            - displayPages: create|edit
              fields:
              - email
              - username
        required: true
      createdAt:
        type: Date
        autoGenerate: true
        ui:
          readOnly: true
          displayAfterField: '-1'
      updatedAt:
        type: Datetime
        autoUpdate: true
        ui:
          readOnly: true
          clientEdit: true
          displayAfterField: '-1'
    relationships:
    - TagAffinity
    ui:
      title: Profile
      buttonLabel: Manage User Profiles
      description: Manage User Preferences
    unique:
    - - name
      - userId
    service: []
  TagAffinity:
    fields:
      tag:
        type: String
        required: true
        max_length: 50
      affinity:
        type: Integer
        required: true
        ge: -100
        le: 100
      createdAt:
        type: Date
        autoGenerate: true
        ui:
          readOnly: true
          displayAfterField: '-1'
      updatedAt:
        type: Datetime
        autoUpdate: true
        ui:
          readOnly: true
          clientEdit: true
          displayAfterField: '-1'
      profileId:
        type: ObjectId
        required: true
    relationships: []
    ui:
      title: Tag Affinity
      buttonLabel: Manage Event Affinity
    unique:
    - - profileId
      - tag
    service: []
  Event:
    fields:
      url:
        type: String
        required: true
        pattern:
          regex: dictionary=main.url
          message: Bad URL format
      title:
        type: String
        required: true
        max_length: 200
      dateTime:
        type: Date
        required: true
      location:
        type: String
        required: false
        max_length: 200
      cost:
        type: Number
        required: false
        ge: 0
        ui:
          displayPages: details
      numOfExpectedAttendees:
        type: Integer
        required: false
        ge: 0
        ui:
          displayPages: details
      recurrence:
        type: String
        required: false
        enum:
          values:
          - daily
          - weekly
          - monthly
          - yearly
        ui:
          displayPages: details
      tags:
        type: Array[String]
        required: false
        ui:
          displayPages: details
      createdAt:
        type: Date
        autoGenerate: true
        ui:
          readOnly: true
          displayAfterField: '-1'
      updatedAt:
        type: Datetime
        autoUpdate: true
        ui:
          readOnly: true
          clientEdit: true
          displayAfterField: '-1'
    relationships:
    - UserEvent
    ui:
      title: Events
      buttonLabel: Manage Events
    unique: []
    service: []
  UserEvent:
    fields:
      attended:
        type: Boolean
        required: false
      rating:
        type: Integer
        required: false
        ge: 1
        le: 5
      note:
        type: String
        required: false
        max_length: 500
        ui:
          displayPages: details
      createdAt:
        type: Date
        autoGenerate: true
        ui:
          readOnly: true
          displayAfterField: '-1'
      updatedAt:
        type: Datetime
        autoUpdate: true
        ui:
          readOnly: true
          clientEdit: true
          displayAfterField: '-1'
      userId:
        type: ObjectId
        required: true
      eventId:
        type: ObjectId
        required: true
    relationships: []
    ui:
      title: User Events
      buttonLabel: Manage Event Attendance
    unique: []
    service: []
  Url:
    fields:
      url:
        type: String
        required: true
        pattern:
          regex: main.url
          message: Bad URL format
      params:
        type: JSON
        required: false
      createdAt:
        type: Date
        autoGenerate: true
        ui:
          readOnly: true
          displayAfterField: '-1'
      updatedAt:
        type: Datetime
        autoUpdate: true
        ui:
          readOnly: true
          clientEdit: true
          displayAfterField: '-1'
    relationships:
    - Crawl
    ui:
      title: Url
      buttonLabel: Manage Urls
      description: Manage Event Urls
    unique: []
    service: []
  Crawl:
    fields:
      lastParsedDate:
        type: Date
        required: false
      parseStatus:
        type: JSON
        required: false
      errorsEncountered:
        type: Array[String]
        required: false
      createdAt:
        type: Date
        autoGenerate: true
        ui:
          readOnly: true
          displayAfterField: '-1'
      updatedAt:
        type: Datetime
        autoUpdate: true
        ui:
          readOnly: true
          clientEdit: true
          displayAfterField: '-1'
      urlId:
        type: ObjectId
        required: true
    relationships: []
    ui:
      title: Crawls
      buttonLabel: Manage Crawls
      description: Manage Crawls of Event sites
    unique: []
    service: []
    operations: rd
