#!/bin/bash
# Comprehensive Validation Test Curl Commands
# Generated by test_validation_live.py
# Run: chmod +x tests/validation_curl.sh && ./tests/validation_curl.sh

echo "=== GET http://localhost:5500/api/user/53f394dcc8c045f1bbf4b970 ==="
curl -X GET "http://localhost:5500/api/user/53f394dcc8c045f1bbf4b970"
echo ""

echo "=== GET http://localhost:5500/api/user/1be5a42f673144dba5125d87 ==="
curl -X GET "http://localhost:5500/api/user/1be5a42f673144dba5125d87"
echo ""

echo "=== GET http://localhost:5500/api/user/55f74bec03184591b1dccfbd ==="
curl -X GET "http://localhost:5500/api/user/55f74bec03184591b1dccfbd"
echo ""

echo "=== GET http://localhost:5500/api/user/55f74bec03184591b1dccfbd?view={"account":["id"]} ==="
curl -X GET "http://localhost:5500/api/user/55f74bec03184591b1dccfbd?view=%7B%22account%22%3A%5B%22id%22%5D%7D"
echo ""

echo "=== GET http://localhost:5500/api/user/5f524b4beef54a5b9492af4a?view={"account":["id"]} ==="
curl -X GET "http://localhost:5500/api/user/5f524b4beef54a5b9492af4a?view=%7B%22account%22%3A%5B%22id%22%5D%7D"
echo ""

echo "=== GET http://localhost:5500/api/user/53f394dcc8c045f1bbf4b970?page=1&pageSize=5&sort=username&order=asc ==="
curl -X GET "http://localhost:5500/api/user/53f394dcc8c045f1bbf4b970?page=1&pageSize=5&sort=username&order=asc"
echo ""

echo "=== GET http://localhost:5500/api/user/5f524b4beef54a5b9492af4a?view={"account":["id"]}&page=1&pageSize=3&sort=createdAt&order=desc ==="
curl -X GET "http://localhost:5500/api/user/5f524b4beef54a5b9492af4a?view=%7B%22account%22%3A%5B%22id%22%5D%7D&page=1&pageSize=3&sort=createdAt&order=desc"
echo ""

echo "=== GET http://localhost:5500/api/user?filter=id:53f394dcc8c045f1bbf4b970&pageSize=5 ==="
curl -X GET "http://localhost:5500/api/user?filter=id:53f394dcc8c045f1bbf4b970&pageSize=5"
echo ""

echo "=== GET http://localhost:5500/api/user?view={"account":["id"]}&filter=id:5f524b4beef54a5b9492af4a&pageSize=3 ==="
curl -X GET "http://localhost:5500/api/user?view=%7B%22account%22%3A%5B%22id%22%5D%7D&filter=id:5f524b4beef54a5b9492af4a&pageSize=3"
echo ""

echo "=== GET http://localhost:5500/api/user?filter=id:1be5a42f673144dba5125d87,gender:male&pageSize=5 ==="
curl -X GET "http://localhost:5500/api/user?filter=id:1be5a42f673144dba5125d87,gender:male&pageSize=5"
echo ""

echo "=== GET http://localhost:5500/api/user/55f74bec03184591b1dccfbd?view={"account":["id","createdAt","updatedAt"]} ==="
curl -X GET "http://localhost:5500/api/user/55f74bec03184591b1dccfbd?view=%7B%22account%22%3A%5B%22id%22%2C%22createdAt%22%2C%22updatedAt%22%5D%7D"
echo ""

