#!/bin/bash
# Comprehensive Validation Test Curl Commands
# Generated by test_validation_live.py
# Run: chmod +x tests/validation_curl.sh && ./tests/validation_curl.sh

echo "=== GET http://localhost:5500/api/user/test_bad_enum_user_123456 ==="
curl -X GET "http://localhost:5500/api/user/test_bad_enum_user_123456"
echo ""

echo "=== GET http://localhost:5500/api/user/test_bad_currency_user_123456 ==="
curl -X GET "http://localhost:5500/api/user/test_bad_currency_user_123456"
echo ""

echo "=== GET http://localhost:5500/api/user/test_bad_fk_user_123456 ==="
curl -X GET "http://localhost:5500/api/user/test_bad_fk_user_123456"
echo ""

echo "=== GET http://localhost:5500/api/user/test_bad_fk_user_123456?view={"account":["id"]} ==="
curl -X GET "http://localhost:5500/api/user/test_bad_fk_user_123456?view=%7B%22account%22%3A%5B%22id%22%5D%7D"
echo ""

echo "=== GET http://localhost:5500/api/user/test_multiple_errors_user_123456?view={"account":["id"]} ==="
curl -X GET "http://localhost:5500/api/user/test_multiple_errors_user_123456?view=%7B%22account%22%3A%5B%22id%22%5D%7D"
echo ""

echo "=== GET http://localhost:5500/api/user/test_bad_enum_user_123456?page=1&pageSize=5&sort=username&order=asc ==="
curl -X GET "http://localhost:5500/api/user/test_bad_enum_user_123456?page=1&pageSize=5&sort=username&order=asc"
echo ""

echo "=== GET http://localhost:5500/api/user/test_multiple_errors_user_123456?view={"account":["id"]}&page=1&pageSize=3&sort=createdAt&order=desc ==="
curl -X GET "http://localhost:5500/api/user/test_multiple_errors_user_123456?view=%7B%22account%22%3A%5B%22id%22%5D%7D&page=1&pageSize=3&sort=createdAt&order=desc"
echo ""

echo "=== GET http://localhost:5500/api/user?filter=id:test_bad_enum_user_123456&pageSize=5 ==="
curl -X GET "http://localhost:5500/api/user?filter=id:test_bad_enum_user_123456&pageSize=5"
echo ""

echo "=== GET http://localhost:5500/api/user?view={"account":["id"]}&filter=id:test_multiple_errors_user_123456&pageSize=3 ==="
curl -X GET "http://localhost:5500/api/user?view=%7B%22account%22%3A%5B%22id%22%5D%7D&filter=id:test_multiple_errors_user_123456&pageSize=3"
echo ""

echo "=== GET http://localhost:5500/api/user?filter=id:test_bad_currency_user_123456,gender:male&pageSize=5 ==="
curl -X GET "http://localhost:5500/api/user?filter=id:test_bad_currency_user_123456,gender:male&pageSize=5"
echo ""

echo "=== GET http://localhost:5500/api/user/test_bad_fk_user_123456?view={"account":["id","createdAt","updatedAt"]} ==="
curl -X GET "http://localhost:5500/api/user/test_bad_fk_user_123456?view=%7B%22account%22%3A%5B%22id%22%2C%22createdAt%22%2C%22updatedAt%22%5D%7D"
echo ""

